#if !canImport(ObjectiveC)
import XCTest

extension MathTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MathTests = [
        ("testLog2", testLog2),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(MathTests.__allTests__MathTests),
    ]
}
#endif
